services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  psql:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    env_file:
      - .env
  
  app:
    build: .
    ports:
      - "80:80"

    environment:
      - ENV=1
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

    depends_on:
      - redis
    restart: always

    env_file:
      - .env


volumes:
  redis_data:  
  postgres_data:
